### ISSUE TITLE
svelte support

### ISSUE THREAD

**Issue by eikaramba** [Yummygum/angular-flag-pack#26]
i understand that targeting vue, react and angular provides most market share. but i would rather develop a library which is independent from the framework. especially when it comes to simple ui elements.

but if that is not an option i would like to propose a framework adapter for svelte as well. should be easy to do i guess

**Comment by eikaramba** [comment]
i'm sorry, i created the issue in the wrong repo and also saw that you already have it ;) https://github.com/Yummygum/svelte-flagpack
will close this now.

**Comment by noudadrichem** [comment]
Also, it's possible to develop for any framework (or non framework) using the flagpack-core package. It has all the assets and is the package all the framework based packages depend/are based upon.
